- .github/workflows/release-publish.yml
> ci: export reference content to `docs` repo

- src/index.ts
> fix: `OracleProvider`

- site/docusaurus.config.js
- site/tsconfig.json
> ci: fix PR to `docs`

- .github/workflows/release-publish.yml
> docs: deployed address

- src/Client.ts
- src/entities/ChromaticAccount.ts
- src/entities/ChromaticLens.ts
- src/entities/ChromaticMarket.ts
- src/entities/ChromaticMarketFactory.ts
- src/entities/ChromaticPosition.ts
- src/entities/ChromaticRouter.ts
- src/entities/lens.spec.ts
> add account entitiy

- .github/workflows/release-publish.yml
> fix: github action

- src/Client.ts
- src/entities/ChromaticAccount.ts
- src/entities/ChromaticLens.ts
- src/entities/ChromaticMarket.ts
- src/entities/ChromaticMarketFactory.ts
- src/entities/ChromaticPosition.ts
- src/entities/ChromaticRouter.ts
- src/entities/index.ts
- src/index.ts
- src/utils/helpers.ts
> refactoring

- src/entities/ChromaticPosition.ts
- src/entities/ChromaticRouter.ts
- src/entities/Positions.spec.ts
> add claimPosition

- src/entities/ChromaticLens.ts
- src/entities/ChromaticRouter.ts
> add lpReceipts to lens

- src/entities/ChromaticPosition.ts
- tsconfig.json
> fix: build error

- src/entities/ChromaticAccount.ts
> docs: typedoc `ChromaticAccount`

- src/entities/ChromaticMarket.ts
> docs: typedoc `ChromaticMarket`

- src/entities/ChromaticMarketFactory.ts
> docs: typedoc `ChromaticMarketFactory`

- src/entities/ChromaticPosition.ts
> docs: typedoc `ChromaticPosition`

- src/entities/ChromaticRouter.ts
> docs: typedoc `ChromaticRouter`

- src/entities/ChromaticLens.ts
> docs: typedoc `ChromaticLens`

- src/Client.ts
> docs: typedoc `Client`

- .github/workflows/release-publish.yml
- package.json
> ci: publish to `npm` registry

- packages/sdk-ethers-v5/package.json
> chore: fix repository-url

- .github/workflows/release-publish-ethers-v5.yml
> ci: fix versioning error

- packages/sdk-viem/src/entities/ChromaticMarket.ts
- packages/sdk-viem/src/utils/helpers.ts
> update viem abi

- packages/sdk-ethers-v5/jest.config.js
- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v5/src/entities/ChromaticMarket.ts
- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v5/src/utils/helpers.ts
- packages/sdk-ethers-v5/test/lens.spec.ts
- packages/sdk-ethers-v5/test/router.spec.ts
- packages/sdk-ethers-v5/test/testHelpers.ts
- packages/sdk-ethers-v6/jest.config.js
- packages/sdk-ethers-v6/src/Client.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticMarket.ts
- packages/sdk-ethers-v6/src/entities/ChromaticMarketFactory.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/utils/helpers.ts
- packages/sdk-ethers-v6/test/lens.spec.ts
- packages/sdk-ethers-v6/test/router.spec.ts
- packages/sdk-ethers-v6/test/testHelpers.ts
- packages/sdk-viem/test/router.spec.ts
> Mark onix/issue144

- packages/sdk-viem/src/utils/helpers.ts
> add facet error signature to viem sdk

- packages/sdk-viem/src/entities/ChromaticLens.ts
> refactor: remove unused code

- packages/sdk-viem/src/utils/helpers.ts
> fix: Duplicated trading fee rates

- packages/sdk-ethers-v5/test/lens.spec.ts
- packages/sdk-ethers-v5/test/router.spec.ts
- packages/sdk-ethers-v5/test/testHelpers.ts
- packages/sdk-ethers-v6/src/utils/helpers.ts
- packages/sdk-ethers-v6/test/Positions.spec.ts
- packages/sdk-ethers-v6/test/lens.spec.ts
- packages/sdk-ethers-v6/test/router.spec.ts
- packages/sdk-ethers-v6/test/testHelpers.ts
- packages/sdk-viem/package.json
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
- packages/sdk-viem/test/Positions.spec.ts
- packages/sdk-viem/test/lens.spec.ts
- packages/sdk-viem/test/router.spec.ts
- packages/sdk-viem/test/testHelpers.ts
> refactor test code

- packages/sdk-ethers-v5/src/entities/ChromaticMarketFactory.ts
- packages/sdk-ethers-v6/src/entities/ChromaticMarketFactory.ts
- packages/sdk-viem/src/entities/ChromaticMarketFactory.ts
> Add method to get oracle provier properties

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
> fix: remove multicall from lens

- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
> fix ChromaticPosition getPnl

- packages/sdk-ethers-v5/src/constants.ts
- packages/sdk-ethers-v5/src/index.ts
- packages/sdk-ethers-v6/src/constants.ts
- packages/sdk-ethers-v6/src/index.ts
- packages/sdk-viem/src/constants.ts
- packages/sdk-viem/src/index.ts
> export constant values

- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
> Invalid closePrice if position not closed

- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
> update comment to ChromaticPosition getPnl

- packages/sdk-viem/src/entities/ChromaticLens.ts
> fix viem lens bigint division

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
> use bigint(viem/ethers-v6) or BigNumber(ethers-v5) type for CLBValue

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v5/test/router.spec.ts
> fix remove PromiseOrValue from ethers v5

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
> refactor `OwnedLiquidityBinResult`

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> add comment interface for docs

- .github/workflows/publish.yml
> ci: distinguish PR tiltes to `docs` repo

- packages/sdk-ethers-v5/src/entities/ChromaticAccount.ts
- packages/sdk-ethers-v6/src/entities/ChromaticAccount.ts
- packages/sdk-viem/src/entities/ChromaticAccount.ts
> fix handle when account is not created

- packages/sdk-viem/src/entities/ChromaticPosition.ts
> fix: `getDeltaForLiquidation` bug

- .github/workflows/publish.yml
> ci: build viem first

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
- packages/sdk-ethers-v6/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
> add pendingLiquidity in ChromaticLens

- packages/sdk-viem/src/utils/helpers.ts
> Mark onix/issue234

- packages/sdk-ethers-v5/src/entities/ChromaticPosition.ts
- packages/sdk-ethers-v6/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
> Using incorrect oracle price for the positions

- .github/workflows/publish.yml
- packages/sdk-ethers-v5/package.json
- packages/sdk-ethers-v6/package.json
- packages/sdk-viem/package.json
> ci: update version at once

- packages/sdk-viem/src/utils/helpers.ts
> fix throw error message with `undefined`

- packages/sdk-ethers-v5/src/utils/helpers.ts
- packages/sdk-ethers-v5/tsconfig.json
- packages/sdk-ethers-v6/src/utils/helpers.ts
- packages/sdk-ethers-v6/tsconfig.json
> fix: type bug

- .github/workflows/publish.yml
> fix publish workflow

- packages/sdk-ethers-v5/src/index.ts
- packages/sdk-ethers-v6/src/index.ts
> chore: export `deployedAddress`

- packages/sdk-ethers-v5/src/entities/ChromaticLens.ts
> fix: parallel contract call in `liquidityBins`

- packages/sdk-viem/codegen/analytics.ts
- packages/sdk-viem/codegen/config/index.ts
- packages/sdk-viem/codegen/lp.ts
- packages/sdk-viem/codegen/performance.ts
- packages/sdk-viem/codegen/position.ts
- packages/sdk-viem/package.json
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/analytics.ts
- packages/sdk-viem/src/lib/graphql/sdk/lp.ts
- packages/sdk-viem/src/lib/graphql/sdk/performance.ts
- packages/sdk-viem/src/lib/graphql/sdk/position.ts
- packages/sdk-viem/test/router.spec.ts
- packages/sdk-viem/tsconfig.build.json
- packages/sdk-viem/tsconfig.cjs.build.json
- yarn.lock
> fix: use graphql client

- packages/sdk-viem/codegen/config/index.ts
- packages/sdk-viem/codegen/lp.ts
- packages/sdk-viem/codegen/subgraph.ts
- packages/sdk-viem/package.json
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/lp.ts
- packages/sdk-viem/src/lib/graphql/sdk/subgraph.ts
- yarn.lock
> Kayden-fi/issue289

- packages/sdk-viem/src/entities/ChromaticLens.ts
> fix: return type

- packages/sdk-viem/package.json
- yarn.lock
> fix: update `viem` version

- packages/sdk-viem/codegen/config/index.ts
- packages/sdk-viem/codegen/lp.ts
- packages/sdk-viem/package.json
- packages/sdk-viem/src/const/index.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/lp.ts
> fix: operation filter condition

- packages/sdk-viem/codegen/subgraph.ts
- packages/sdk-viem/src/const/index.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/subgraph.ts
- packages/sdk-viem/test/lens.spec.ts
> fix: clbTotalSupply graphql query

- packages/sdk-viem/src/lib/graphql/index.ts
> fix: remove `operationName`` from header

- packages/sdk-viem/codegen/subgraph.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/subgraph.ts
> fix: add where

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> Add check allowance after approve

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> Add gasLimit to open/close position

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> Fix approve settlement amount

- packages/sdk-viem/codegen/analytics.ts
- packages/sdk-viem/codegen/lp.ts
- packages/sdk-viem/codegen/performance.ts
- packages/sdk-viem/codegen/position.ts
- packages/sdk-viem/codegen/subgraph.ts
- packages/sdk-viem/package.json
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/lib/graphql/index.ts
- packages/sdk-viem/src/lib/graphql/sdk/analytics.ts
- packages/sdk-viem/src/lib/graphql/sdk/lp.ts
- packages/sdk-viem/src/lib/graphql/sdk/performance.ts
- packages/sdk-viem/src/lib/graphql/sdk/position.ts
- packages/sdk-viem/src/lib/graphql/sdk/subgraph.ts
- yarn.lock
> fix graphql-request dependency

- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/lib/graphql/index.ts
> CORS errors on fetching liquidity bins

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/const/index.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> adjust gasLimit of tx wrt position/liquidity

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/const/index.ts
> fix: increase gas limit of tx wrt LP

- packages/sdk-viem/src/entities/ChromaticRouter.ts
> fix: claim position

- packages/sdk-viem/package.json
> fix: add missing `graphql-tag`

- packages/sdk-ethers-v5/src/entities/ChromaticRouter.ts
- packages/sdk-ethers-v6/src/entities/ChromaticRouter.ts
- packages/sdk-viem/src/entities/ChromaticRouter.ts
> fix: Token allowances #326

- packages/sdk-viem/src/const/index.ts
> change graphql endpoint

- packages/sdk-viem/src/const/index.ts
- packages/sdk-viem/src/entities/ChromaticLens.ts
- packages/sdk-viem/src/entities/ChromaticPosition.ts
- packages/sdk-viem/src/lib/graphql/index.ts
> branching subgraph endpoints ( arbitrum sepolia, arbtirum one )

- .github/workflows/publish.yml
> chore: ci node20
